Add BDC-Auth and git submodule
brazil-data-cube/lccs-ws pull request #48
Opened 2021-02-03 17:04 UTC by fabianazioti

2021-02-03 17:43 UTC, raphaelrpl requested changes

2021-02-03 17:43 UTC, raphaelrpl commented on setup.py
>      'Werkzeug>=0.16.1,<1', # Temp workaround https://github.com/noirbizarre/flask-restplus/issues/777
Since the bdc-core and flask-restplus are not being used. Could you review this dependency? It seems unused for me since Flask >= 1.1 install the latest werkzeug package

2021-02-04 11:30 UTC, fabianazioti commented on setup.py
>      'Werkzeug>=0.16.1,<1', # Temp workaround https://github.com/noirbizarre/flask-restplus/issues/777
> Since the `bdc-core` and `flask-restplus` are not being used. Could you review this dependency `werkzeug>=0.16.1,<1` ? It seems unused for me since Flask >= 1.1 install the latest `werkzeug` package

dependency removed!

2021-02-04 12:09 UTC, raphaelrpl approved these changes

2021-02-05 12:39 UTC, gqueiroz requested changes

2021-02-05 12:39 UTC, gqueiroz commented on lccs_ws/version.py
> +__version__ = '0.6.0-0'
Please, change to 0.6.0 only. The spec will be named just 0.6.

2021-02-05 12:39 UTC, gqueiroz commented on .gitmodules
> +	path = docs/lccs-ws-spec
Please check if it is 04 space indented.

2021-02-06 21:54 UTC, M3nin0 approved these changes

2021-02-07 22:24 UTC, gqueiroz requested changes

2021-02-07 22:24 UTC, gqueiroz commented on .drone.yml
> +  image: postgres:12.2
Let's use the Docker image: `postgis/postgis:13-3.1`.

2021-02-08 18:18 UTC, gqueiroz approved these changes

2021-02-08 18:18 UTC, merged