Update service based on spec
brazil-data-cube/lccs-ws pull request #54
Opened 2021-02-10 10:44 UTC by fabianazioti

2021-02-10 15:11 UTC, raphaelrpl requested changes

2021-02-10 15:11 UTC, raphaelrpl commented on lccs_ws/data.py
> +    source_class = db.session.query(LucClass). \
Move the `.` to the next line like the others

2021-02-10 15:11 UTC, raphaelrpl commented on lccs_ws/views.py
> +    return {'message': 'created'}, 201
Is it according to lccs-ws-spec?

2021-02-11 11:48 UTC, raphaelrpl approved these changes

2021-02-11 18:47 UTC, gqueiroz approved these changes

2021-02-11 18:48 UTC, gqueiroz approved these changes

2021-02-11 18:48 UTC, merged